# Generated by Django 6.0.2 on 2026-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_harmfulingredient_ingredientscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientscan',
            name='input_method',
            field=models.CharField(choices=[('scan', 'Scanned'), ('manual', 'Manual')], default='manual', max_length=10),
            preserve_default=False,
        ),
    ]
